apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: database
spec:
  clusterIP: None   # lowercase!
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

